[package]
name = "wasm-shared-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.92"
js-sys = "0.3"
wasm-bindgen-rayon = "1.0.5"
rayon = "1.8"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console"] }

[lib]
crate-type = ["cdylib"]
